routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use Illuminate\Http\Request;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

/** Frontend Routing */
Route::prefix('/')->group(function () {
    Route::get('/', 'Site\HomeController@index')->name('home');
    Route::get('/summoners-wars-chronicles', 'Site\HomeController@swchronicles')->name('chronicles');
    Route::get('/about', 'Site\HomeController@about')->name('about');
    Route::get('/about/guild', 'Site\HomeController@guild')->name('about-the-guild');
    Route::get('/about/game', 'Site\HomeController@game')->name('about-the-game');

    /** Contact Form */
    Route::get('/contact', 'Admin\ContatoController@index')->name('contact');
	Route::post('/contact', 'Admin\ContatoController@send');

    Route::get('/message-listing',  ['middleware' => 'auth', 'uses' => 'Admin\ContatoController@list'])->name('message-listing');
});

/** Backend Routing */
Route::prefix('painel')->group(function () {
Route::get('/', 'Admin\HomeController@index')->name('painel');

/* Members Routing */
Route::resource('/members', 'Admin\MemberController');
});

Auth::routes();

app/Member.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Member extends Model
{
    /*
     * Belongs to Labirinto
     */
    public function labirinto(){
        return $this->belongsTo('App\Labirinto','id');
    }

    /*
     * Belongs to Guild Wars
     */
    public function gvg(){
        return $this->belongsTo('App\Gvg','id');
    }

    /*
     * Belongs to Siege
     */
    public function siege(){
        return $this->belongsTo('App\Siege','id');
    }
}

app/Http/Controllers/Admin/MemberController.php
<?php

namespace App\Http\Controllers\Admin;

use Illuminate\Http\Request;
use App\Member;

class MemberController extends Controller
{
    public function __construct(){
        $this->middleware('auth');
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $members = Member::orderBy('nome', 'ASC')->paginate(15);

        $loggedId = intval(Auth::id());

        return view('admin.members.index', [
            'members' => $members,
            'loggedId' => $loggedId
        ]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('admin.members.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $data = $request->only([
            'nome',
            'conta_principal',
            'conta_alt',
            'in_gvg',
            'in_siege'
        ]);

        $validator = Validator::make($data, [
            'nome' => ['required', 'string', 'max:100'],
            'conta_principal' => ['required', 'string', 'max:100', 'unique:members'],
            'conta_alt' => ['string', 'max:100', 'unique:members'],
            'in_gvg' => ['required', 'boolean'],
            'in_siege' => ['required', 'boolean']
        ]);

        if ($validator->fails()){
            return redirect()->route('admin.members.create')
            ->withErrors($validator)
            ->withInput();
        }

        $member = new Member;
        $member->nome = $data['nome'];
        $member->conta_principal = $data['conta_principal'];
        $member->conta_alt = $data['conta_alt'];
        $member->in_gvg = $data['in_gvg'] == 'true' ? 1 : 0;
        $member->in_siege = $data['in_siege'] == 'true' ? 1 : 0;
        $member->save();

        return redirect()->route('admin.members.index');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
}

resources/views/admin/members/create.blade.php
@extends('layouts.backend')

@section('title', 'Cadastrar Membro')

@section('content_header')
<h1>Novo Membro</h1>
@endsection

@section('mainArea')

@if($errors->any())
<div class="alert alert-danger">
    <h5> <i class="icon fa s fa-ban"></i> Alerta! </h5>
    <ul>
        @foreach($errors->all() as $error)
        <li>{{ $error }}</li>
        @endforeach
    </ul>
</div>
@endif

<div class="card">
    <div class="card-body">
        <form action="{{ route('members.store') }}" method="post" class="form-horizontal">
            @csrf
            <div class="form-group row">
                <label for="name" class="col-form-label col-sm-2">Nome :</label>
                <div class="col-sm-10">
                    <input type="text" name="nome" id="nome" class="form-control @error('nome') is-invalid @enderror"
                        value="{{ old('nome') }}">
                </div>
            </div>

            <div class="form-group row">
                <label for="conta_principal" class="col-form-label col-sm-2">Conta #1:</label>
                <div class="col-sm-10">
                    <input type="text" name="conta_principal" id="conta_principal"
                        class="form-control @error('conta_principal') is-invalid @enderror" value="{{ old('conta_principal') }}">
                </div>
            </div>

            <div class="form-group row">
                <label for="conta_alt" class="col-form-label col-sm-2">Conta #2:</label>
                <div class="col-sm-10">
                    <input type="text" name="conta_alt" id="conta_alt"
                        class="form-control @error('conta_alt') is-invalid @enderror">
                </div>
            </div>

            <div class="form-group row">
                <label for="in_gvg" class="col-form-label col-sm-2">Está na GvG?</label>
                <div class="col-sm-10">
                    <input type="radio" name="password_confirmation" id="password_confirmation"
                        class="form-control @error('password') is-invalid @enderror">
                </div>
            </div>

            <div class="form-group row">
                <label for="addNewUser" class="col-form-label col-sm-2"></label>
                <div class="col-sm-10">
                    <input type="submit" name="addNewUser" id="addNewUser" value="Cadastrar" class="btn btn-success">
                </div>
            </div>
        </form>
    </div>
</div>

@endsection

resources/views/admin/members/index.blade.php
@extends('layouts.backend')

@section('title', 'Membros')

@section('content_header')
<h1>Meus Usuários
    <a href="{{ route('members.create') }}" class="btn btn-sm btn-success ml-3 text-uppercase">Adicionar Usuário</a>
</h1>
@endsection

@section('mainArea')

<div class="card">
    <div class="card-body">
        <table class="table table-hover">
            <thead>
                <tr>
                    <th>ID</th>
                    <th>Nome</th>
                    <th>Conta #1</th>
                    <th>Conta #2</th>
                    <th>Está na GvG</th>
                    <th>Está na Siege?</th>
                    <th>Ações</th>
                </tr>
            </thead>

            <tbody>
                @foreach ($members as $member)
                <tr>
                    <th>{{ $member->id }}</th>
                    <th>{{ $member->nome }}</th>
                    <th>{{ $member->conta_principal }}</th>
                    <th>{{ $member->conta_alt }}</th>
                    <th>{{ $member->in_gvg }}</th>
                    <th>{{ $member->in_siege }}</th>
                    <th>
                        <a href="{{ route('members.edit', ['member' => $member->id]) }}"
                            class="btn btn-sm btn-info">Editar</a>

                        @if ($loggedId !== intval($member->id))
                        <form action="{{ route('members.destroy', ['member' => $member->id]) }}" method="POST"
                            class="d-inline" onsubmit="return confirm('Tem certeza que deseja excluir este usuário?')">
                            @csrf
                            @method('DELETE')
                            <input type="submit" value="Excluir" class="btn btn-sm btn-danger">
                            @endif
                        </form>
                    </th>
                </tr>
                @endforeach
            </tbody>
        </table>
    </div>
</div>

{{$members->links()}}

@endsection